// utils/handleConfirmBuild.ts
import { getMvpStream } from "../lib/api";
import sanitizeMessages from "./sanitizeMessages";

type UpdateIdeaFn = (id: any, updates: any) => void;
type SetDeployLogsFn = (logs: string[]) => void;

export default function createConfirmBuildHandler(
  updateIdea: UpdateIdeaFn,
  setDeployLogs: SetDeployLogsFn,
  ideas: any[]
) {
  const simulateStreamingLog = (ideaId: string, line: string) => {
    updateIdea(ideaId, (prev: any) => ({
      ...prev,
      messages: [
        ...(prev.messages || []),
        { role: "assistant", content: line }
      ]
    }));
  };

  return async function handleConfirmBuild(id: any) {
    const idea = ideas.find((i) => i.id === id);
    if (!idea || !idea.takeaways?.branding || !idea.messages?.length) {
      updateIdea(id, {
        deployError: "Missing ideaId, branding, or messages",
      });
      return;
    }

    updateIdea(id, { deploying: true });
    setDeployLogs([]);

    let messageAccumulator = [...idea.messages];

    const appendLog = (line: string) => {
      messageAccumulator = [
        ...messageAccumulator,
        { role: "assistant", content: line },
      ];
      simulateStreamingLog(id, line);
    };

    updateIdea(id, {
      messages: [
        ...messageAccumulator,
        { role: "assistant", content: "🚀 Beginning MVP build and deployment..." },
      ],
    });

    try {
      await getMvpStream(
        idea.id,
        idea.takeaways.branding,
        sanitizeMessages(idea.messages),
        // onLog
        (log) => {
          setDeployLogs((prev) => [...prev, log]);
          appendLog(log);
        },
        // onDone
        (data) => {
          const { pagesUrl, repoUrl, plan } = data || {};

          if (pagesUrl) {
            const finalLine = `✅ Deployment successful!

🔗 [Live Site](${pagesUrl})  
📁 [GitHub Repo](${repoUrl || "https://github.com"})`;

            appendLog(finalLine);
            updateIdea(id, {
              deploying: false,
              deployed: true,
              repoUrl: repoUrl || "",
              pagesUrl,
            });
          } else if (plan) {
            appendLog("✅ Here’s the MVP build plan generated by the agent:\n\n" + plan);
            updateIdea(id, {
              deploying: false,
              takeaways: {
                ...idea.takeaways,
                finalPlan: plan,
              },
            });
          } else {
            appendLog("⚠️ Deployment completed but no URL or plan was returned.");
            updateIdea(id, { deploying: false });
          }
        },
        // onError
        (errMsg) => {
          appendLog(`❌ Deployment failed: ${errMsg}`);
          updateIdea(id, {
            deploying: false,
            deployError: errMsg,
          });
        }
      );
    } catch (err: any) {
      const errMsg = err instanceof Error ? err.message : String(err);
      appendLog(`❌ Deployment failed: ${errMsg}`);
      updateIdea(id, {
        deploying: false,
        deployError: errMsg,
      });
    }
  };
}