name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'
      - 'wrangler.toml'
      - '.github/workflows/deploy-worker.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish Worker
        run: wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
