name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'
      - 'wrangler.toml'
      - '.github/workflows/deploy-worker.yml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish Worker with Vars
        run: |
          wrangler publish \
            --var OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --var PAT_GITHUB="${{ secrets.PAT_GITHUB }}"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
